### ISSUE TITLE
It should use Google Analytics to track active users

### ISSUE THREAD

**Issue by ProfJanetDavis** [glam-lab/degender-the-web#53]
Pavel Sapehin [recommends](https://medium.com/@pavel.sapehin/lessons-learned-from-developing-a-paid-chrome-extension-5642148d7363) using [Google Analytics](https://marketingplatform.google.com/about/analytics/) [for Chrome extensions](https://github.com/googlearchive/chrome-platform-analytics). 

### Why would we want to do this?
1. To count the active users of the extension. Reportedly, the Chrome Web Store already tracks the number of installed users on the [Developer Dashboard](https://chrome.google.com/webstore/developer/dashboard) using weekly update requests. However, this [almost certainly overestimates](https://stackoverflow.com/questions/37656276/chrome-webstore-extensions-download-statistic) of the number of people actually using the app by counting, for example, those who have the extension installed but disabled. 
1. To track how frequently extension features are used. Since apps report their own actions, it could report "actions" button presses, but it could also report which code paths are taken independent of user actions. 
1. To identify when original content is restored for the same page over and over across many users, or when the extension is frequently disabled for a page or domain. I'm also soliciting that information explicitly through GitHub Issues (make a template specifically for this!) but it might be helpful to have that information collected automatically.
1. **To store evaluation data (see #24).**

### Why would it be okay to do this?
[Google Analytics Policy](https://developers.google.com/analytics/devguides/collection/protocol/policy) forbids the collection of PII, requires transparency in the form of a privacy policy, and requires user consent and the opportunity to opt out. This is wholly consistent with Common Rule procedures for research with human participants.

### Why would we not do this?
1. The privacy policy is clearer and less scary without mentioning Google Analytics.
1. Though the information it provides might help focus development efforts or make for a nicer story, I haven't yet formulated research questions that it would be answering. This makes the information superfluous. It also makes it hard to justify data collection in an IRB proposal. **ETA: Chrome Analytics should be a suitable approach to storing evaluation data, with user consent.**
1. Collecting information through other means (the Chrome Store Web Dashboard, GitHub Issues) should be good enough **to know something about app usage**. Use the least invasive, most voluntary data collection procedures until they are shown to be inadequate.
1. It actually seems to be a bit [technically challenging](https://gusperez.com/wp/2015/09/using-google-analytics-on-a-chrome-extension/). It might not be easy to make it work. I don't want to hold up the IRB proposal while figuring it out. **ETA: The initial IRB proposal was submitted and approved. It would be nice to know if this is going to work before writing the first amendment.**

### Why might we nonetheless want to do this before Release 1.0?
Avoid bait-and-switch. We could lose users by changing the privacy policy post-installation. Worse, users may not read the new policy.

### TODO
- [x] Find and do relevant tutorials.
- [ ] Figure out an implementation plan and write it here!
- [ ] Address it in the [privacy policy](https://github.com/glam-lab/degender-the-web/blob/master/PRIVACY.md). 
- [ ] Add the Google Analytics ID to the app listing on the [Chrome Web Store Developer Dashboard](https://chrome.google.com/webstore/developer/dashboard) with the next release.

**Comment by beszel** [comment]
With some fumbling, I've managed to make Google Analytics work for the extension. I've used the popup (from a yet-unresolved PR) as a testing ground, since page views are an easy way to get started. Next I'll move it over to the main script so I'm not making my changes on unmerged code, and also so that we can count users who don't use the popup.

The only user being counted right now is me (spamming the popup), since I'm the only one running a tracked version of the extension:
![analytics](https://user-images.githubusercontent.com/23243513/68068081-3ad64080-fd0e-11e9-96da-1ffa07631457.png)

- Which actions do we want to track?
  - Button activations, popup usage, any time the content script runs
- Is a "page view" event the right way to track when the content script runs? I imagine there's a better option.
- How and when should I pass over control of the Google Analytics account? I can add another user to the account or else the tracking ID can be changed to point to a new account.

**Comment by ProfJanetDavis** [comment]
Can we meet so you can walk through your code changes? A conversation might also help me think through what is useful to track. 

I'm using the account degender.the.web@gmail.com for the Google Developer Dashboard. I'd like to use that account here too. I'm not sure whether it makes more sense to add another user or point to a new account - let's discuss when we meet.

**Comment by beszel** [comment]
Sure thing! I'll email about meeting.
