### ISSUE TITLE
It should show changes/highlights only when requested by the user

### ISSUE THREAD

**Issue by ProfJanetDavis** [glam-lab/degender-the-web#91]
**Is your feature request related to a problem? Please describe.**
This redesign/refactoring will resolve issues #15, #63, #86.

**Describe the solution you'd like**
- By default, pronouns and associated verbs will be replaced without markup.
- For transparency and debugging, the header will include a button to show changes using [diff-style notation](https://johnresig.com/projects/javascript-diff-algorithm/).
- Similarly, stop words will be highlighted only when the user clicks a button.

**Describe alternatives you've considered**
I considered putting the original tooltips back (#6). That would serve transparency less well, since you would only be able to see one change at a time. That would also require more extensive modifications to the diff implementation above.

**Rationale**
This approach will make changes more visible and easier to read when the user asks to see them, and totally invisible otherwise.

This approach will separate markup from natural language processing, resulting in more modular and readable code.

**Implementation plan**
This will be a significant, user-visible change requiring changes to both unit tests and end-to-end tests. Practice test-driven development!
- [x] Make a feature branch.
- [x] Remove the HTML markup from `replacePronouns`, modifying unit tests and end-to-end tests accordingly. 
- [x] Remove everything related to pronouns from `word-replacement.js`
- [x] Remove everything related to capitalization from `word-repalcements.js`
- [x] Replace the existing dgtw-replacement style class with two new style classes: `dgtw-insertion` and `dgtw-deletion`. For clarity, use strikethrough in the deletion class. Make sure color choices are accessible. 
- [x] Adapt [this code](https://johnresig.com/projects/javascript-diff-algorithm/) (or some other Javascript diff implementation) to show changes. This code doesn't use style classes, but that seems easy to change.
- [x] Make a new header button to toggle whether changes are highlighted. That button should also toggle whether stop words are highlighted. It should not be shown if there is nothing to highlight. (Thus, all five major use cases are impacted.)
- [x] Move grammar tests to the unit test suite, where they will run much faster! 
- [x] Refactor `main()`.
- [x] Do some manual testing!
- [x] Update the readme and bump the intermediate version number.
- [x] Clean up with `git rebase -i`.
- [ ] Merge to master and tag a release.
- [ ] Post to the Chrome Web Store?

**Additional context**
Since it involves the header buttons, this issue will interact with #68. There are no particular implications for implementation order, but whichever is completed later will need to account for the one completed first.

**Comment by ProfJanetDavis** [comment]
@irhawk, what do you think of this proposal?

**Comment by beszel** [comment]
This solution seems fine, I can't think of a better way to show changes. Could you tell me about when the user needs the diff mode? I like it for debugging; does it also help with transparency?

**Comment by ProfJanetDavis** [comment]
Yes, it's important that users be able to understand what the algorithm has changed. Being able to restore the original text goes some distance toward that, but people are not very good at comparing texts in their head. 

Thanks!
